# Generated by Django 2.2 on 2020-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=100)),
                ('det', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('soft', models.IntegerField(max_length=100)),
                ('softprice', models.IntegerField(max_length=100)),
                ('hard', models.IntegerField(max_length=100)),
                ('hardprice', models.IntegerField(max_length=100)),
                ('noseat', models.IntegerField(max_length=100)),
                ('noseatprice', models.IntegerField(max_length=100)),
            ],
        ),
    ]
