# Generated by Django 2.2 on 2020-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='bought_ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=100)),
                ('tsrc', models.CharField(max_length=100)),
                ('tdet', models.CharField(max_length=100)),
                ('tdate', models.DateField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('realname', models.CharField(max_length=100)),
                ('idnum', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='num',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hard',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hardprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='noseat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='noseatprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='soft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='softprice',
            field=models.IntegerField(),
        ),
    ]
