# Generated by Django 2.2 on 2020-05-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200522_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='noseat',
            new_name='hardseat',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='noseatprice',
            new_name='hardseatprice',
        ),
    ]
