# Generated by Django 2.2 on 2020-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_bought_ticket_buytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hardprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hardseatprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='softprice',
            field=models.CharField(max_length=100),
        ),
    ]
