# Generated by Django 2.2 on 2020-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_admincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='modify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
    ]
