# Generated by Django 2.2 on 2020-05-26 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='modify',
            name='modifytime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
