# Generated by Django 2.2 on 2020-05-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_modify_modifytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modify',
            name='tname',
        ),
    ]
