# Generated by Django 2.2 on 2020-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_modify_tname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincode',
            name='idnum',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincode',
            name='realname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
