# Generated by Django 2.2 on 2020-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200526_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='modify',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
