# Generated by Django 2.2 on 2020-05-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_modify_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='password2',
        ),
    ]
