# Generated by Django 2.2 on 2020-05-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_registry_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='password1',
            new_name='password',
        ),
    ]
